name: main

on:
  push:
    branches:
    - main

jobs:
  build:
    name: 'JDK=${{ matrix.java }} | AGP=${{ matrix.agp }} | KT=${{ matrix.kotlin }} | GRADLE=${{ matrix.gradle }} | OKHTTP=${{ matrix.okhttp }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11, 19]
        kotlin: [1.8.10, 1.8.20-RC2]
        agp: [7.4.2, 8.1.0-alpha10]
        gradle: [7.6.1, 8.1-rc-1]
        okhttp: [3.14.9, 4.10.0, 5.0.0-alpha.11]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Setup gradle ${{ matrix.gradle }}
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: ${{ matrix.gradle }}

      - run: gradle test --stacktrace -PagpVersion=${{ matrix.agp }} -PkotlinVersion=${{ matrix.kotlin }} -PokHttpVersion=${{ matrix.okhttp }}